### ISSUE TITLE
SDSC: PKG - expanse/0.17.3/cpu/a - Missing cp2k (example application)

### ISSUE THREAD

**Issue by nwolter** [sdsc/spack#35]
This is one of our example applications

**Comment by mkandes** [comment]
@jerrypgreenberg - A reminder. We may need to re-tune cp2k at some point in the future. If I recall correctly, we ran into this lmax tuning in the past.

```
[spack_cpu@exp-15-56 openmpi@4.1.3]$ spack info libint
AutotoolsPackage:   libint

Description:
    Libint is a high-performance library for computing Gaussian integrals in
    quantum mechanics.

Homepage: https://github.com/evaleev/libint

Maintainers: @dev-zero

Externally Detectable: 
    False

Tags: 
    None

Preferred version:  
    2.6.0    https://github.com/evaleev/libint/archive/v2.6.0.tar.gz

Safe versions:  
    2.6.0    https://github.com/evaleev/libint/archive/v2.6.0.tar.gz
    2.4.2    https://github.com/evaleev/libint/archive/v2.4.2.tar.gz
    2.4.1    https://github.com/evaleev/libint/archive/v2.4.1.tar.gz
    2.4.0    https://github.com/evaleev/libint/archive/v2.4.0.tar.gz
    2.2.0    https://github.com/evaleev/libint/archive/v2.2.0.tar.gz
    2.1.0    https://github.com/evaleev/libint/archive/v2.1.0.tar.gz
    1.1.6    https://github.com/evaleev/libint/archive/release-1-1-6.tar.gz
    1.1.5    https://github.com/evaleev/libint/archive/release-1-1-5.tar.gz

Deprecated versions:  
    None

Variants:
    Name [Default]    When    Allowed values          Description
    ==============    ====    ====================    =============================================================================

    debug [off]       --      on, off                 Enable building with debug symbols
    fma [off]         --      on, off                 Generate code utilizing FMA (requires capable CPU and recent enough compiler)
    fortran [off]     --      on, off                 Build & install Fortran bindings
    tune [none]       --      none, cp2k-lmax-4,      Tune libint for use with the given package
                              cp2k-lmax-5,            
                              cp2k-lmax-6,            
                              cp2k-lmax-7, molgw-     
                              lmax-4, molgw-          
                              lmax-5, molgw-          
                              lmax-6, molgw-lmax-7    

Installation Phases:
    autoreconf    configure    build    install

Build Dependencies:
    autoconf  automake  boost  gmp  gnuconfig  libtool

Link Dependencies:
    boost  gmp

Run Dependencies:
    None

Virtual Packages: 
    None

[spack_cpu@exp-15-56 openmpi@4.1.3]$
```

**Comment by jerrypgreenberg** [comment]
Yes, I remember that.

Also, I posted the spack load problem to slack spack gripes

Jerry

From: Marty Kandes ***@***.***>
Date: Tuesday, April 4, 2023 at 8:25 AM
To: sdsc/spack ***@***.***>
Cc: Greenberg, Jerry ***@***.***>, Mention ***@***.***>
Subject: Re: [sdsc/spack] SDSC: PKG - expanse/0.17.3/cpu/a - Missing cp2k (example application) (Issue #35)

@jerrypgreenberg<https://urldefense.com/v3/__https:/github.com/jerrypgreenberg__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHcalpnPmg$> - A reminder. We may need to re-tune cp2k at some point in the future. If I recall correctly, we ran into this lmax tuning in the past.

***@***.*** ***@***.***$ spack info libint

AutotoolsPackage:   libint



Description:

    Libint is a high-performance library for computing Gaussian integrals in

    quantum mechanics.



Homepage: https://github.com/evaleev/libint<https://urldefense.com/v3/__https:/github.com/evaleev/libint__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHeFAm2Tnw$>



Maintainers: @dev-zero



Externally Detectable:

    False



Tags:

    None



Preferred version:

    2.6.0    https://github.com/evaleev/libint/archive/v2.6.0.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/v2.6.0.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHfFHyEgBw$>



Safe versions:

    2.6.0    https://github.com/evaleev/libint/archive/v2.6.0.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/v2.6.0.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHfFHyEgBw$>

    2.4.2    https://github.com/evaleev/libint/archive/v2.4.2.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/v2.4.2.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHeAE5pfbQ$>

    2.4.1    https://github.com/evaleev/libint/archive/v2.4.1.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/v2.4.1.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHe0S1DIvg$>

    2.4.0    https://github.com/evaleev/libint/archive/v2.4.0.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/v2.4.0.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHejZFNi9g$>

    2.2.0    https://github.com/evaleev/libint/archive/v2.2.0.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/v2.2.0.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHdBhIfuPA$>

    2.1.0    https://github.com/evaleev/libint/archive/v2.1.0.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/v2.1.0.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHcvUT_9Nw$>

    1.1.6    https://github.com/evaleev/libint/archive/release-1-1-6.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/release-1-1-6.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHdvw4G_dA$>

    1.1.5    https://github.com/evaleev/libint/archive/release-1-1-5.tar.gz<https://urldefense.com/v3/__https:/github.com/evaleev/libint/archive/release-1-1-5.tar.gz__;!!Mih3wA!Fjq_iNneSq351XlIVC81Uw7uCzpWW33iC1MZ-KI93l_8WqnsGqd_Ko8Gku68LEIgXbXb3oyHA4twaHe9co6Lgg$>



Deprecated versions:

    None



Variants:

    Name [Default]    When    Allowed values          Description

    ==============    ====    ====================    =============================================================================



    debug [off]       --      on, off                 Enable building with debug symbols

    fma [off]         --      on, off                 Generate code utilizing FMA (requires capable CPU and recent enough compiler)

    fortran [off]     --      on, off                 Build & install Fortran bindings

    tune [none]       --      none, cp2k-lmax-4,      Tune libint for use with the given package

                              cp2k-lmax-5,

                              cp2k-lmax-6,

                              cp2k-lmax-7, molgw-

                              lmax-4, molgw-

                              lmax-5, molgw-

                              lmax-6, molgw-lmax-7



Installation Phases:

    autoreconf    configure    build    install



Build Dependencies:

    autoconf  automake  boost  gmp  gnuconfig  libtool



Link Dependencies:

    boost  gmp



Run Dependencies:

    None



Virtual Packages:

    None



***@***.*** ***@***.***$

**Comment by mkandes** [comment]
@nwolter - Ready for testing.

```
[spack_cpu@login02 ~]$ module list

Currently Loaded Modules:
  1) slurm/expanse/21.08.8   6) amdfftw/3.1/zqoqbjf
  2) aocc/3.2.0/io3s466      7) amdlibflame/3.1/f37pl2z
  3) ucx/1.10.1/gxh7r4c      8) amdscalapack/3.1/olerfv5
  4) openmpi/4.1.3/6bxpzag   9) cp2k/7.1/zszhu77
  5) amdblis/3.1/6sfatsa

[spack_cpu@login02 ~]$
```

**Comment by nwolter** [comment]
I might have missed something but with module spider cp2k/7.1  It does not include all the modules you have listed above.  Is this a problem?

login02 ~]$ module spider cp2k/7.1

---------------------------------------------------------------------------------------------------------------
  cp2k/7.1: cp2k/7.1/zszhu77
---------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "cp2k/7.1/zszhu77" module is available to load.

      aocc/3.2.0/io3s466  openmpi/4.1.3/6bxpzag

**Comment by nwolter** [comment]
Just for completeness when I load the listed modules I get 
[nickel@login02 ~]$ module load aocc/3.2.0
[nickel@login02 ~]$ module load openmpi/4.1.3
[nickel@login02 ~]$ module list

Currently Loaded Modules:
  1) slurm/expanse/21.08.8   3) aocc/3.2.0/io3s466   5) openmpi/4.1.3/6bxpzag
  2) sdsc/1.0                4) ucx/1.10.1/gxh7r4c

**Comment by mkandes** [comment]
@nwolter - No, it's not a problem. In general, you should only have to load the compiler, mpi, and the application module to get all of the required modules loaded. i.e., we are trying to autoload everything for the user as much as possible.

```
[mkandes@login01 ~]$ module purge
[mkandes@login01 ~]$ module load slurm
[mkandes@login01 ~]$ module use /cm/shared/apps/spack/0.17.3/cpu/a/share/spack/lmod/linux-rocky8-x86_64/Core
[mkandes@login01 ~]$ module list

Currently Loaded Modules:
  1) slurm/expanse/21.08.8

 

[mkandes@login01 ~]$ module load aocc/3.2.0
[mkandes@login01 ~]$ module load openmpi/4.1.3
[mkandes@login01 ~]$ module load cp2k/7.1
[mkandes@login01 ~]$ module list

Currently Loaded Modules:
  1) slurm/expanse/21.08.8   6) amdfftw/3.1/zqoqbjf
  2) aocc/3.2.0/io3s466      7) amdlibflame/3.1/f37pl2z
  3) ucx/1.10.1/gxh7r4c      8) amdscalapack/3.1/olerfv5
  4) openmpi/4.1.3/6bxpzag   9) cp2k/7.1/zszhu77
  5) amdblis/3.1/6sfatsa

 

[mkandes@login01 ~]$
```

**Comment by nwolter** [comment]
@mkandes sorry I had already figured that out and deleted the comment.  Too many spinning plates.....

**Comment by nwolter** [comment]
example scripts work fine
