### ISSUE TITLE
SDSC: PKG - expanse/0.17.3/cpu/b - Missing gamess  (example application)

### ISSUE THREAD

**Issue by nwolter** [sdsc/spack#36]
This is a example application

**Comment by mkandes** [comment]
@nwolter - Ready for testing.

```
[mkandes@login01 ~]$ module load gamess/2021.09
[mkandes@login01 ~]$ module list

Currently Loaded Modules:
  1) slurm/expanse/21.08.8   4) openmpi/4.1.3/4ejofw7
  2) gcc/10.2.0/npcyll4      5) openblas/0.3.18/w4zdqc3-i64
  3) ucx/1.10.1/kfriyyt      6) gamess/2021.09/be77mka

[mkandes@login01 ~]$
```

**Comment by mkandes** [comment]
```
[mkandes@exp-15-56 ~]$ module spider gamess/2021.09/eo5efva

----------------------------------------------------------------------------
  gamess/2021.09: gamess/2021.09/eo5efva
----------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "gamess/2021.09/eo5efva" module is available to load.

      cpu/0.17.3b  gcc/10.2.0/npcyll4  openmpi/4.1.3/oq3qvsv
 

 

[mkandes@exp-15-56 ~]$ module load gcc/10.2.0/npcyll4
[mkandes@exp-15-56 ~]$ module load openmpi/4.1.3/oq3qvsv
[mkandes@exp-15-56 ~]$ module load gamess/2021.09/eo5efva 
[mkandes@exp-15-56 ~]$ module list

Currently Loaded Modules:
  1) shared                      6) gcc/10.2.0/npcyll4
  2) cpu/0.17.3b           (c)   7) ucx/1.10.1/dnpjjuc
  3) slurm/expanse/21.08.8       8) openmpi/4.1.3/oq3qvsv
  4) sdsc/1.0                    9) openblas/0.3.18/w4zdqc3
  5) DefaultModules             10) gamess/2021.09/eo5efva

  Where:
   c:  built natively for AMD Rome

 

[mkandes@exp-15-56 ~]$
```

**Comment by nwolter** [comment]
This module not available in /b yet on regular login nodes?  Should I test on exp-15-56?  
Do I have the wrong path?
```
[nickel@login01 cpu]$ module purge
[nickel@login01 cpu]$ module use module use /cm/shared/apps/spack/0.17.3/cpu/a/share/spack/lmod/linux-rocky8-x86_64/Core
[nickel@login01 cpu]$ module spider gamess/2021.09/eo5efva
Lmod has detected the following error:  Unable to find: "gamess/2021.09/eo5efva".
```

`[nickel@login02 ~]$ module purge
[nickel@login02 ~]$ module user module use /cm/shared/apps/spack/0.17.3/cpu/a/share/spack/lmod/linux-rocky8-x86_64/Core
[nickel@login02 ~]$ module spider gamess/2021.09/eo5efva

  gamess/2021.09: gamess/2021.09/eo5efva

    You will need to load all module(s) on any one of the lines below before the "gamess/2021.09/eo5efva" module is available to load.

      gcc/10.2.0/npcyll4  openmpi/4.1.3/oq3qvsv

If I dont use #
73 ]$ module spider gamess/2021.09

---------------------------------------------------------------------------------------------------------------------------------------
  gamess/2021.09: gamess/2021.09/be77mka
---------------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "gamess/2021.09/be77mka" module is available to load.

      gcc/10.2.0/npcyll4  openmpi/4.1.3/4ejofw7



`

**Comment by nwolter** [comment]
script tested:
example script available at:
/expanse/lustre/projects/use300/nickel/2023/gamess/cpu/run.sb
