### ISSUE TITLE
SDSC: PKG - expanse/0.17.3/cpu/b - Missing matlab (example application)

### ISSUE THREAD

**Issue by nwolter** [sdsc/spack#39]
This is an example application

**Comment by mkandes** [comment]
@nwolter - Matlab is ready for testing.

```
[mkandes@exp-9-55 ~]$ module purge
[mkandes@exp-9-55 ~]$ module load slurm
[mkandes@exp-9-55 ~]$ module use /cm/shared/apps/spack/0.17.3/cpu/a/share/spack/lmod/linux-rocky8-x86_64/Core
[mkandes@exp-9-55 ~]$ module load matlab/2022b/lefe4oq 
[mkandes@exp-9-55 ~]$ matlab
MATLAB is selecting SOFTWARE OPENGL rendering.

                            < M A T L A B (R) >
                  Copyright 1984-2022 The MathWorks, Inc.
             R2022b Update 2 (9.13.0.2105380) 64-bit (glnxa64)
                              October 26, 2022

 
To get started, type doc.
For product information, visit www.mathworks.com.
 
>>
```

**Comment by nwolter** [comment]
WE spoke of this last friday and I am still getting OOM error when running with new version
module purge
module load sdsc
module use /cm/shared/apps/spack/0.17.3/cpu/a/share/spack/lmod/linux-rocky8-x86_64/Core
module load matlab/2022b

.(tail of output)
.
.
>> >> >> >> /cm/local/apps/slurm/var/spool/job21734689/slurm_script: line 17: 3474577 Killed                  matlab -nojvm -nodisplay -nosplash < UsingTimeSeriestoPredictEquityReturnExample.m
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=21734689.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by nwolter** [comment]
matlab sample script tested.  
available at: 
/expanse/lustre/projects/use300/nickel/2023/matlab/matlab.sb

(what is the best/easist way to provide the scripts for updating /cm/shared?)
