### ISSUE TITLE
SDSC: PKG - expanse/0.17.3/cpu/a - Missing ORCA (example application)

### ISSUE THREAD

**Issue by nwolter** [sdsc/spack#40]

**Comment by mkandes** [comment]
@nwolter - I've installed the latest version of ORCA. Please test when you get a chance. Thanks.

```
[mkandes@login02 ~]$ module purge
[mkandes@login02 ~]$ module load slurm
[mkandes@login02 ~]$ module use /cm/shared/apps/spack/0.17.3/cpu/a/share/spack/lmod/linux-rocky8-x86_64/Core
[mkandes@login02 ~]$ module load gcc/10.2.0
[mkandes@login02 ~]$ module load openmpi/4.1.1
[mkandes@login02 ~]$ module load orca/5.0.4
[mkandes@login02 ~]$ which orca
/cm/shared/apps/spack/0.17.3/cpu/a/opt/spack/linux-rocky8-zen2/gcc-10.2.0/orca-5.0.4-kunhxhora2h6vwm2av3dcclodazmblxa/bin/orca
[mkandes@login02 ~]$
```

**Comment by nwolter** [comment]
Example Orca test(appears to be Carbon Monoxide) successful using Orca5.0.4. But   run is less then 6 seconds.  Should I find something that runs longer for this application for benchmarking?

**Comment by mkandes** [comment]
@nwolter - There is this 'testsuite' you could look at ... if you need another set of tests. I haven't looked at it and don't know if there is a more substantial benchmark test available within.

```
[spack_cpu@exp-15-56 packages]$ ls ~/software/orca/
orca_4_2_1_linux_x86-64_shared_openmpi314.tar.xz
orca_5_0_3_linux_x86-64_shared_openmpi411.tar.xz
orca_5_0_4_linux_x86-64_shared_openmpi411.tar.xz
testsuite_orca_5_0_4.zip
```

**Comment by nwolter** [comment]
@mkandes do you have testsujite somewhere already on the system that I can pick it up or should I download from orca site?
