### ISSUE TITLE
SDSC: PKG - expanse/0.17.3/cpu/b - Missing gromacs(example application)

### ISSUE THREAD

**Issue by nwolter** [sdsc/spack#58]

**Comment by mkandes** [comment]
Ready for testing.

```
[mkandes@login02 ~]$ module spider gromacs/2020.4

----------------------------------------------------------------------------
  gromacs/2020.4:
----------------------------------------------------------------------------
     Versions:
        gromacs/2020.4/m7rlauu
        gromacs/2020.4/vw5c4m3

----------------------------------------------------------------------------
  For detailed information about a specific "gromacs/2020.4" package (including how to load the modules) use the module's full name. Note that names that have a trailing (E) are extensions provided by other modules.
  For example:

     $ module spider gromacs/2020.4/vw5c4m3
----------------------------------------------------------------------------

 

[mkandes@login02 ~]$
```

**Comment by nwolter** [comment]
aocc example works ok

**Comment by nwolter** [comment]
If I use the hash at end of modules, I get error: 
For example
`cpu]$ cat gromacs-2020.4_gcc-expanse-cpu.22080466.out
Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "openmpi/4.1.3/4ejofw7"
   Try: "module spider openmpi/4.1.3/4ejofw7" to see how to load the module(s).



Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "gromacs/2020.4/m7rlauu"
   Try: "module spider gromacs/2020.4/m7rlauu" to see how to load the
module(s).

Currently Loaded Modules:
  1) slurm/expanse/21.08.8   2) gcc/10.2.0/npcyll4

login02 cpu]$ module spider gromacs/2020.4/m7rlauu

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  gromacs/2020.4: gromacs/2020.4/m7rlauu
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "gromacs/2020.4/m7rlauu" module is available to load.

      gcc/10.2.0/npcyll4  openmpi/4.1.3/4ejofw7

`
If I dont include the hash the wrong modules are picked up. 
 cpu]$ cat gromacs-2020.4_aocc-expanse-cpu.22081254.out

Currently Loaded Modules:
  1) slurm/expanse/21.08.8   5) amdblis/3.1/6sfatsa
  2) aocc/3.2.0/io3s466      6) amdfftw/3.1/t757st4
  3) ucx/1.10.1/wla3unl      7) amdlibflame/3.1/f37pl2z
  4) openmpi/4.1.3/xigazqd   8) gromacs/2020.4/2ufeq67-omp

**Comment by nwolter** [comment]
Versions change in /b ,  but they these look good in /b
`[nickel@login02 ~]$ module spider gromacs/2020.4

-----------------------------------------------------------------------------------------------------------------------------------------
  gromacs/2020.4:
-----------------------------------------------------------------------------------------------------------------------------------------
     Versions:
        gromacs/2020.4/2ufeq67-omp
        gromacs/2020.4/65gq3je-omp
`

**Comment by nwolter** [comment]
gcc:  Ok
aocc:  OK
scripts located at:
/expanse/lustre/projects/use300/nickel/2023/gromacs/cpu/gromacs-2node-256c_aocc.sb
/expanse/lustre/projects/use300/nickel/2023/gromacs/cpu/gromacs-2node-256c_gcc.sb
