### ISSUE TITLE
SDSC: PKG - expanse/0.17.3/gpu/b - Missing matlab (example application)

### ISSUE THREAD

**Issue by nwolter** [sdsc/spack#67]
------------------------------------------------------------------------------------------------------------------------------------
  matlab: matlab/2020b
------------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "matlab/2020b" module is available to load.

      cpu/0.15.4
      gpu/0.15.4

**Comment by mkandes** [comment]
@nwolter - What is the note about the loading of both modules? Is this a problem you're observing in the `expanse/0.15.4` instances?

**Comment by nwolter** [comment]
Sorry.......not sure why I copied the module list?  too many thoughts and then got distracted.  Still getting the OOM error,  unless I set mem in batch script.  It is fine to set mem to 1G ?????

**Comment by nwolter** [comment]
To summary matlab appears good,  but need to adjust example script to include mem

**Comment by mkandes** [comment]
Ready for testing in `expanse/0.17.3/gpu/b`

**Comment by nwolter** [comment]
example script ok
available at:
/expanse/lustre/projects/use300/nickel/2023/matlab/matlab-gpu.sb
